-- TAG
DROP TABLE IF EXISTS Tag;
CREATE TABLE Tag(
	name CHAR(64) PRIMARY KEY,
	color CHAR(16) NOT NULL
);
-- MEDIA
DROP TABLE IF EXISTS Media;
CREATE TABLE Media(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	textAlternatif TEXT NOT NULL,
	url TEXT NOT NULL,
	width DOUBLE,
	height DOUBLE
);

-- USER
DROP TABLE IF EXISTS User;
CREATE TABLE User(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username CHAR(255),
	email CHAR(255) NOT NULL,
	role CHAR(10) CHECK(role IN ('USER', 'AUTHOR')) NOT NULL DEFAULT 'USER',

	-- AUTH
	totpSeed CHAR(255),

	-- AUTHOR
	picture INTEGER,
	link TEXT,

	-- USER
	subscribedAt TIMESTAMP,
	isSupporter BOOLEAN NOT NULL DEFAULT 0,

	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

	FOREIGN KEY(picture) REFERENCES Media(id)
);

-- SPONSOR
DROP TABLE IF EXISTS Sponsor;
CREATE TABLE Sponsor(
	name CHAR(255) PRIMARY KEY,
	link TEXT NOT NULL
);

-- ISSUE
DROP TABLE IF EXISTS Issue;
CREATE TABLE Issue (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	slug CHAR(255) NOT NULL,
	title CHAR(255) NOT NULL,
	subtitle CHAR(255) NOT NULL,
	cover INTEGER,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	publishedAt TIMESTAMP,
	updatedAt TIMESTAMP,
	issueNumber UNSIGNED INT NOT NULL,
	excerpt TEXT NOT NULL,
	content TEXT NOT NULL,
	isSponsored BOOLEAN DEFAULT 0,
	status CHAR(10) CHECK(status IN ('DRAFT', 'PUBLISHED', 'ARCHIVE')) DEFAULT 'DRAFT' NOT NULL,
	openedMailCount INTEGER DEFAULT 0 NOT NULL,
	FOREIGN KEY(cover) REFERENCES Media(id)
);

-- ISSUETAG
DROP TABLE IF EXISTS IssueTag;
CREATE TABLE IssueTag(
	tagName CHAR(64) NOT NULL,
	issueId INTEGER NOT NULL,
	FOREIGN KEY(issueId) REFERENCES Issue(id),
	FOREIGN KEY(tagName) REFERENCES Tag(name),
	PRIMARY KEY(tagName, issueId)
);

-- ISSUEAUTHOR
DROP TABLE IF EXISTS IssueAuthor;
CREATE TABLE IssueAuthor(
	authorName CHAR(255) NOT NULL,
	issueId INTEGER NOT NULL,
	FOREIGN KEY(issueId) REFERENCES Issue(id),
	FOREIGN KEY(authorName) REFERENCES Author(name),
	PRIMARY KEY(authorName, issueId)
);

-- ISSUESPONSOR
DROP TABLE IF EXISTS IssueSponsor;
CREATE TABLE IssueSponsor(
	sponsorName CHAR(255) NOT NULL,
	issueId INTEGER NOT NULL,
	link TEXT NOT NULL,
	FOREIGN KEY(issueId) REFERENCES Issue(id),
	FOREIGN KEY(sponsorName) REFERENCES Sponsor(name),
	PRIMARY KEY(sponsorName, issueId)
);

-- VIEW
DROP TABLE IF EXISTS View;
CREATE TABLE View(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	hashedIp TEXT NOT NULL,
	issueId INTEGER NOT NULL,
	FOREIGN KEY(issueId) REFERENCES Issue(id)
);
